- hosts: all
  gather_facts: no
  vars:
      http_port: 8080
      max_clients: 200
      mysql_admin_username: admin_user
      mysql_admin_password: YOURPASSWORD
    
  pre_tasks:
      - name: install python 2
        become: yes
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:

      - name: Install MySQL
        apt: pkg={{item}} update_cache=yes cache_valid_time=86400 state=present
        become: yes
        with_items:
        - mysql-server

      - name: Install MySql Python
        become: yes
        apt: 
          name: python-mysqldb
          state: latest

#      - name: Change mysql config to start in unsafe mode
#        copy:
#          src: ./my.cnf.unsafe
#          dest: /etc/mysql/mysql.cnf
#          owner: root
#          group: root
#          mode: 644
#        become: yes
        
#      - name: Restart mysql service
#        become: yes
#        service: name=mysql state=restarted

#      - name: Set Mysql Root Password
#        command: mysql -uroot -e"UPDATE mysql.user SET authentication_string=PASSWORD('{{ mysql_root_password }}'), plugin='mysql_native_password' WHERE USER='root'";
#        become: yes

#      - name: Secure MYSQL Installation
#        command: mysql_secure_installation --use-default
#        become: yes

      - name: Create Admin User
        command: mysql -uroot -e"GRANT ALL PRIVILEGES ON *.* TO '{{ mysql_admin_username }}'@'localhost' IDENTIFIED BY '{{ mysql_admin_password }}'";
        become: yes

#      - name: Change mysql config to start in safe mode
#        copy:
#          src: ./my.cnf
#          dest: /etc/mysql/mysql.cnf
#          owner: root
#          group: root
#          mode: 644
#        become: yes
#        
#      - name: Restart mysql service
#        become: yes
#        service: name=mysql state=restarted

#      - name: configuring root user pass and priveliges
#        mysql_user: login_user=root name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
#        with_items:
#        - 127.0.0.1
#        - ::1
#        - localhost

      - name: Install HTTPD
        apt:
          name: apache2
          state: latest
        become: yes

      - name: Install PHP
        apt: pkg={{item}}
        become: yes
        with_items:
        - libapache2-mod-php
        - php-mcrypt
        - php-mysql
        - php-mbstring
        - php7.0-mbstring
        - php-gettext
        - libapache2-mod-php7.0
        
      - name: Install PHPMyAdmin
        apt: 
          name: phpmyadmin
          state: latest
        become: yes

      - name: Configure Apache to run PHPMyAdmin
        copy:
          src: ./apache2.conf
          dest: /etc/apache2/apache2.conf
          owner: root
          group: root
          mode: 644
        become: yes
        
      - name: Reload Apache Confirguration
        command: apachectl -k graceful
        become: yes

      - name: Download Joomla
        get_url:
          url: https://downloads.joomla.org/cms/joomla3/3-8-7/Joomla_3-8-7-Stable-Full_Package.tar.gz?format=gz
          dest: /tmp/Joomla.tar.gz

      - name: Clean /var/www/html folder
        file:
          state: absent
          path: /var/www/html/*
        become: yes

      - name: Extract Joomla tar.gz file into 
        unarchive:
          src: /tmp/Joomla.tar.gz
          dest: /var/www/html/
          remote_src: yes
        become: yes

