- hosts: all
  gather_facts: no
  vars:
      http_port: 8080
      max_clients: 200
      mysql_admin_username: admin_user
      mysql_admin_password: YOURPASSWORD
    
  pre_tasks:
      - name: install python 2
        become: yes
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:

      - name: Install MySQL
        apt: pkg={{item}} update_cache=yes cache_valid_time=86400 state=present
        become: yes
        with_items:
        - mysql-server

      - name: Install MySql Python
        become: yes
        apt: 
          name: python-mysqldb
          state: latest

#      - name: Secure MYSQL Installation
#        command: mysql_secure_installation --use-default
#        become: yes

      - name: Create Admin User
        command: mysql -uroot -e"GRANT ALL PRIVILEGES ON *.* TO '{{ mysql_admin_username }}'@'localhost' IDENTIFIED BY '{{ mysql_admin_password }}'";
        become: yes

      - name: Install Apache2
        apt:
          name: apache2
          state: latest
        become: yes

      - name: Install Apache2 mod_security
        apt:
          name: libapache2-mod-security2
          state: latest
        become: yes

      - name: Setup mod_security config file
        copy:
          src: ./modsecurity.conf
          dest: /etc/modsecurity/
          mode: 0644
        become: yes

      - name: Setup mod_security Core Ruleset
        copy:
          src: ./security2.conf
          dest: /etc/apache2/mods-available/
          owner: root
          group: root
          mode: 644
        become: yes
        
      - name: Enable SQL Injection Mod Security Rule
        file:
          src: /usr/share/modsecurity-crs/base_rules/modsecurity_crs_41_sql_injection_attacks.conf
          dest: /usr/share/modsecurity-crs/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf
          state: link
        become: yes

      - name: Install PHP
        apt: pkg={{item}}
        become: yes
        with_items:
        - libapache2-mod-php
        - php-mcrypt
        - php-mysql
        - php-mbstring
        - php7.0-mbstring
        - php-gettext
        - libapache2-mod-php7.0

      - name: Configure PHP Security
        copy:
          src: ./php.ini
          dest: /etc/php/7.0/apache2/php.ini
          owner: root
          group: root
          mode: 644
        become: yes
        
      - name: Install PHPMyAdmin
        apt: 
          name: phpmyadmin
          state: latest
        become: yes

      - name: Configure Apache to run PHPMyAdmin
        copy:
          src: ./apache2.conf
          dest: /etc/apache2/apache2.conf
          owner: root
          group: root
          mode: 644
        become: yes
        
      - name: Reload Apache Confirguration
        command: apachectl -k graceful
        become: yes

      - name: Download Joomla
        get_url:
          url: https://downloads.joomla.org/cms/joomla3/3-8-7/Joomla_3-8-7-Stable-Full_Package.tar.gz?format=gz
          dest: /tmp/Joomla.tar.gz

      - name: Clean /var/www/html folder
        file:
          state: absent
          path: /var/www/html/index.html
        become: yes

      - name: Extract Joomla tar.gz file into 
        unarchive:
          src: /tmp/Joomla.tar.gz
          dest: /var/www/html/
          remote_src: yes
        become: yes

